from datetime import date
from uuid import uuid4

from .audit import AuditTrail
from .domain import (
    ConflictError,
    InvalidTransition,
    NotFoundError,
    ValidationError,
)
from .rules import (
    RuleEngine,
    build_sanction_period,
    date_in_ranges,
    evaluate_eligibility,
    parse_date,
)


REQUIRED_CASEBACKFILL = ("months",)


class DomainService:
    def __init__(self, repository, rules=None):
        self.repository = repository
        self.rules = rules or RuleEngine()
        self.audit = AuditTrail(repository)

    def _lookup(self, kind, field, value):
        return self.repository.find_entities(self.rules.normalize_kind(kind), field, value)

    def health(self):
        return {"status": "ok" if self.repository.ping() else "error"}

    # ------------------------------------------------------------------
    # Creation
    # ------------------------------------------------------------------

    def create(self, actor, kind, data, idempotency_key=None):
        kind = self.rules.normalize_kind(kind)
        payload = dict(data or {})
        if kind in self.rules.SYSTEM_KINDS:
            raise ValidationError("%s records are generated by the system" % kind)
        with self.repository.transaction() as store:
            if idempotency_key:
                existing = store.get_idempotency(actor.user_id, idempotency_key)
                if existing:
                    entity = store.get_entity(existing)
                    if entity:
                        return entity
            self.rules.validate_create(actor, kind, payload, self._store_lookup(store))
            entity_id = str(payload.pop("id", "") or uuid4())
            if store.get_entity(entity_id):
                raise ConflictError("entity already exists: " + entity_id)
            status = self.rules.initial_status(kind)
            entity = store.create_entity(entity_id, kind, status, payload, actor.user_id)
            self.audit.record(entity_id, actor, "create", None, status,
                              {"kind": kind}, store=store)
            rejection = None
            if kind == "competition_result":
                rejection = self._guard_competition(actor, entity, store)
            if idempotency_key:
                store.save_idempotency(actor.user_id, idempotency_key, entity_id)
        if rejection is not None:
            # The original result is kept (committed as rejected); the caller
            # is still told the registration was refused.
            raise rejection
        return self.repository.get_entity(entity_id)

    def _store_lookup(self, store):
        def lookup(kind, field, value):
            return store.find_entities(self.rules.normalize_kind(kind), field, value)
        return lookup

    def _guard_competition(self, actor, result, store):
        """Read the sanction periods in force at the event date or reject."""
        athlete_id = result["data"]["athlete_id"]
        event_day = parse_date(result["data"]["event_date"])
        decision = evaluate_eligibility(
            athlete_id,
            event_day,
            store.find_entities("sanction", "athlete_id", athlete_id),
            store.find_entities("comeback_test", "athlete_id", athlete_id),
        )
        result["data"]["eligibility_check"] = {
            "checked_at": date.today().isoformat(),
            "result": "blocked" if not decision["eligible"] else "eligible",
            "reason": decision["reason"],
        }
        if not decision["eligible"]:
            # The result is kept on record but rejected: no original result
            # is overwritten, the athlete never becomes eligible through it.
            store.update_entity(result["id"], 1, "rejected", result["data"])
            self.audit.record(
                result["id"], actor, "register_blocked", "registered", "rejected",
                {"reason": decision["reason"], "detail": decision["detail"]},
                store=store,
            )
            return ValidationError(
                "result rejected: athlete is not eligible on %s (%s)"
                % (result["data"]["event_date"], decision["reason"])
            )
        return None

    # ------------------------------------------------------------------
    # Transitions
    # ------------------------------------------------------------------

    def transition(self, actor, entity_id, action, data=None, expected_version=None):
        data = dict(data or {})
        with self.repository.transaction() as store:
            entity = store.get_entity(entity_id)
            if not entity:
                raise NotFoundError("entity not found: " + entity_id)
            kind = self.rules.normalize_kind(entity["kind"])

            if kind == "case":
                return self._case_transition(
                    actor, entity, action, data, expected_version, store
                )
            if kind == "sanction":
                return self._sanction_transition(
                    actor, entity, action, data, expected_version, store
                )

            expected = int(expected_version) if expected_version is not None else entity["version"]
            next_status, patch = self.rules.validate_transition(
                actor, entity, action, data, self._store_lookup(store)
            )
            merged = dict(entity["data"])
            merged.update(patch)
            updated = store.update_entity(entity_id, expected, next_status, merged)
            self.audit.record(
                entity_id, actor, action, entity["status"], updated["status"],
                {"patch": patch}, store=store,
            )
            return updated

    def _case_transition(self, actor, case, action, data, expected_version, store):
        expected = int(expected_version) if expected_version is not None else case["version"]
        lookup = self._store_lookup(store)

        if action == "provisional_suspend" and case["status"] in ("open", "suspended"):
            next_status, patch = self.rules.validate_transition(
                actor, case, action, data, lookup
            )
            suspension_id = "prov-%s-%s" % (case["id"], uuid4().hex[:8])
            suspension = store.create_entity(
                suspension_id, "provisional_suspension", "in_force",
                {
                    "athlete_id": case["data"]["athlete_id"],
                    "case_id": case["id"],
                    "reason": patch.get("reason", ""),
                    "started_at": parse_date(patch["started_at"]).isoformat(),
                    "created_by": actor.user_id,
                },
                actor.user_id,
            )
            merged = dict(case["data"])
            merged.update(patch)
            merged["started_at"] = suspension["data"]["started_at"]
            updated = store.update_entity(case["id"], expected, "suspended", merged)
            self.audit.record(
                suspension_id, actor, "create", None, "in_force",
                {"kind": "provisional_suspension", "case_id": case["id"]},
                store=store,
            )
            self.audit.record(
                case["id"], actor, action, case["status"], "suspended",
                {"patch": patch, "provisional_suspension_id": suspension_id},
                store=store,
            )
            return updated

        if action == "lift_provisional":
            next_status, patch = self.rules.validate_transition(
                actor, case, action, data, lookup
            )
            lifted = self._close_active_provisionals(
                store, case["id"], actor,
                ended=date.today().isoformat(),
                status="revoked",
                audit_action="revoke_provisional",
                reason=patch.get("reason", ""),
            )
            merged = dict(case["data"])
            merged.update(patch)
            updated = store.update_entity(case["id"], expected, "open", merged)
            self.audit.record(
                case["id"], actor, action, "suspended", "open",
                {"patch": patch, "lifted": lifted}, store=store,
            )
            return updated

        next_status, patch = self.rules.validate_transition(
            actor, case, action, data, lookup
        )

        if action in ("decide", "resolve_appeal"):
            decision_day = self._decision_day(case, patch)
            if action == "decide":
                patch["decision_date"] = decision_day.isoformat()
            self._close_active_provisionals(
                store, case["id"], actor,
                ended=decision_day.isoformat(),
                status="in_force",
                audit_action="complete_provisional",
            )
            merged = dict(case["data"])
            merged.update(patch)
            updated = store.update_entity(case["id"], expected, "closed", merged)
            self.audit.record(
                case["id"], actor, action, case["status"], "closed",
                {"patch": patch}, store=store,
            )
            self._apply_decision(actor, updated, patch, decision_day, store)
            return updated
        if action == "schedule_hearing":
            merged = dict(case["data"])
            merged.update(patch)
            updated = store.update_entity(case["id"], expected, next_status, merged)
            self.audit.record(
                case["id"], actor, action, case["status"], next_status,
                {"patch": patch}, store=store,
            )
            return updated

        # appeal and any other transitions
        merged = dict(case["data"])
        merged.update(patch)
        updated = store.update_entity(case["id"], expected, next_status, merged)
        self.audit.record(
            case["id"], actor, action, case["status"], next_status,
            {"patch": patch}, store=store,
        )
        return updated

    @staticmethod
    def _decision_day(case, patch):
        if patch.get("decision_date"):
            day = parse_date(patch["decision_date"])
        elif case["data"].get("decision_date"):
            day = parse_date(case["data"]["decision_date"])
        else:
            day = date.today()
        if day > date.today():
            raise ValidationError("decision_date cannot be in the future")
        return day

    def _close_active_provisionals(self, store, case_id, actor, ended, status,
                                   audit_action, reason=None):
        ids = []
        for item in store.find_entities("provisional_suspension", "case_id", case_id):
            if item["status"] != "in_force":
                continue
            data = dict(item["data"])
            if not data.get("ended_at"):
                data["ended_at"] = ended
            if reason is not None:
                data["lift_reason"] = reason
            store.update_entity(item["id"], item["version"], status, data)
            self.audit.record(
                item["id"], actor, audit_action, "in_force", status,
                {"ended_at": data["ended_at"]}, store=store,
            )
            ids.append(item["id"])
        return ids

    def _apply_decision(self, actor, case, patch, decision_day, store):
        athlete_id = case["data"]["athlete_id"]
        existing = store.find_entities("sanction", "case_id", case["id"])
        revision = 1 + max((s["data"].get("revision", 0) for s in existing), default=0)
        prior_active = [
            s for s in existing
            if s["status"] in ("active", "pending_backfill")
        ]

        if patch["decision"] != "sanction":
            for sanction in prior_active:
                self._supersede(
                    store, sanction, actor,
                    reason="appeal resolved as no_sanction",
                    period=None,
                )
            return

        period = self._compute_period(
            case, int(patch["months"]), decision_day, athlete_id, store
        )
        prior_ids = [s["id"] for s in prior_active]
        if prior_active:
            for sanction in prior_active:
                self._supersede(
                    store, sanction, actor,
                    reason="revised by appeal decision",
                    period=None,
                )
        sanction = store.create_entity(
            "sanction-%s-r%d-%s" % (case["id"], revision, uuid4().hex[:8]),
            "sanction",
            "active",
            {
                "athlete_id": athlete_id,
                "case_id": case["id"],
                "revision": revision,
                "decided_by": actor.user_id,
                "supersedes": prior_ids,
                **period,
            },
            actor.user_id,
        )
        self.audit.record(
            sanction["id"], actor, "create", None, "active",
            {"kind": "sanction", "case_id": case["id"], "revision": revision,
             "period": {key: period[key] for key in
                        ("months", "raw_end", "credited_days", "adjusted_end")}},
            store=store,
        )
        annulled = self._annul_results(store, sanction, actor)
        store.update_entity(sanction["id"], sanction["version"], "active",
                            {**sanction["data"], "annulled_results": annulled})

    def _sanction_transition(self, actor, sanction, action, data, expected_version, store):
        if action != "backfill":
            raise InvalidTransition("unknown action %s for sanction" % action)
        if sanction["status"] != "pending_backfill":
            raise InvalidTransition(
                "cannot backfill from status %s" % sanction["status"]
            )
        self.rules._ensure_role(
            actor, self.rules.ROLE_ACTIONS.get("backfill", ("admin",))
        )
        self.rules._require(data, REQUIRED_CASEBACKFILL)
        months_value = data["months"]
        if isinstance(months_value, bool) or not isinstance(months_value, int) or months_value <= 0:
            raise ValidationError("months must be a positive integer")

        case = store.get_entity(sanction["data"]["case_id"])
        if not case:
            raise NotFoundError("case for pending sanction not found")
        decision_day = parse_date(case["data"].get("decision_date") or date.today().isoformat())
        if decision_day > date.today():
            raise ValidationError("decision_date cannot be in the future")
        expected = int(expected_version) if expected_version is not None else sanction["version"]
        period = self._compute_period(
            case, int(months_value), decision_day,
            sanction["data"]["athlete_id"], store,
        )
        updated_data = dict(sanction["data"])
        updated_data.update(period)
        updated_data["months"] = int(months_value)
        updated_data["decided_by"] = actor.user_id
        updated_data["backfilled_by"] = actor.user_id
        updated = store.update_entity(sanction["id"], expected, "active", updated_data)
        self.audit.record(
            sanction["id"], actor, "backfill", "pending_backfill", "active",
            {"period": {key: period[key] for key in
                        ("months", "raw_end", "credited_days", "adjusted_end")}},
            store=store,
        )
        annulled = self._annul_results(store, updated, actor)
        final_data = dict(updated["data"])
        final_data["annulled_results"] = annulled
        store.update_entity(updated["id"], updated["version"], "active", final_data)
        return store.get_entity(sanction["id"])

    def _compute_period(self, case, months, decision_day, athlete_id, store):
        all_provisionals = store.find_entities(
            "provisional_suspension", "athlete_id", athlete_id
        )
        already_credited = []
        for other in store.find_entities("sanction", "athlete_id", athlete_id):
            if other["status"] != "active":
                continue
            if other["data"].get("case_id") == case["id"]:
                continue
            for credit in other["data"].get("credit_ranges", []):
                already_credited.append(
                    (parse_date(credit["start"]), parse_date(credit["end"]))
                )
        return build_sanction_period(
            case, months, decision_day, all_provisionals, already_credited
        )

    def _supersede(self, store, sanction, actor, reason, period):
        data = dict(sanction["data"])
        data["superseded_reason"] = reason
        store.update_entity(
            sanction["id"], sanction["version"], "superseded", data
        )
        self.audit.record(
            sanction["id"], actor, "supersede", sanction["status"], "superseded",
            {"reason": reason}, store=store,
        )

    def _annul_results(self, store, sanction, actor):
        """Annul every registered result caught by the sanction's windows."""
        ranges = [
            (parse_date(r["start"]), parse_date(r["end"]))
            for r in sanction["data"].get("blocked_ranges", [])
        ]
        annulled = list(sanction["data"].get("annulled_results", []))
        for result in store.find_entities(
            "competition_result", "athlete_id", sanction["data"]["athlete_id"]
        ):
            # Only accepted results are annulled; rejected registrations never
            # became results in the first place, and annulled ones stay so.
            if result["status"] != "registered":
                continue
            event_day = parse_date(result["data"]["event_date"])
            if not date_in_ranges(event_day, ranges):
                continue
            data = dict(result["data"])
            data["annulled"] = True
            data["annulled_by_sanction"] = sanction["id"]
            store.update_entity(result["id"], result["version"], "annulled", data)
            self.audit.record(
                result["id"], actor, "annul_result", result["status"], "annulled",
                {"sanction_id": sanction["id"], "event_date": data["event_date"]},
                store=store,
            )
            annulled.append({
                "result_id": result["id"],
                "event": data.get("event"),
                "event_date": data["event_date"],
                "placing": data.get("placing"),
            })
        return annulled

    # ------------------------------------------------------------------
    # Reads
    # ------------------------------------------------------------------

    def get(self, entity_id):
        entity = self.repository.get_entity(entity_id)
        if not entity:
            raise NotFoundError("entity not found: " + entity_id)
        return entity

    def list(self, kind=None, status=None):
        if kind:
            kind = self.rules.normalize_kind(kind)
        return self.repository.list_entities(kind=kind, status=status)

    def athlete_eligibility(self, athlete_id, on_date=None):
        with self.repository.transaction(immediate=False) as store:
            athlete = store.get_entity(athlete_id)
            if not athlete:
                raise NotFoundError("athlete not found: " + athlete_id)
            day = parse_date(on_date) if on_date else date.today()
            sanctions = store.find_entities("sanction", "athlete_id", athlete_id)
            tests = store.find_entities("comeback_test", "athlete_id", athlete_id)
            decision = evaluate_eligibility(athlete_id, day, sanctions, tests)
            return {
                "athlete_id": athlete_id,
                "athlete": athlete,
                "evaluated_on": day.isoformat(),
                "eligible": decision["eligible"],
                "reason": decision["reason"],
                "detail": decision["detail"],
                "sanctions": [self._sanction_view(s) for s in
                              sorted(sanctions, key=lambda s: s["created_at"])],
                "comeback_tests": [
                    {
                        "id": t["id"],
                        "test_date": t["data"].get("test_date"),
                        "result": t["data"].get("result"),
                        "status": t["status"],
                    }
                    for t in sorted(tests, key=lambda t: t["data"]["test_date"])
                ],
                "results": [
                    {
                        "id": r["id"],
                        "event": r["data"].get("event"),
                        "event_date": r["data"].get("event_date"),
                        "placing": r["data"].get("placing"),
                        "status": r["status"],
                    }
                    for r in store.find_entities(
                        "competition_result", "athlete_id", athlete_id
                    )
                ],
            }

    @staticmethod
    def _sanction_view(sanction):
        data = sanction["data"]
        return {
            "id": sanction["id"],
            "case_id": data.get("case_id"),
            "status": sanction["status"],
            "revision": data.get("revision"),
            "months": data.get("months"),
            "decision_date": data.get("decision_date"),
            "raw_start": data.get("raw_start"),
            "raw_end": data.get("raw_end"),
            "adjusted_end": data.get("adjusted_end"),
            "credited_days": data.get("credited_days"),
            "credit_ranges": data.get("credit_ranges", []),
            "blocked_ranges": data.get("blocked_ranges", []),
            "supersedes": data.get("supersedes", []),
            "superseded_reason": data.get("superseded_reason"),
            "annulled_results": data.get("annulled_results", []),
        }

    def audit_log(self, entity_id=None):
        return self.repository.list_audit(entity_id=entity_id)
